7 develop episode 2
esciencecenter-digital-skills/Natural-language-processing pull request #12
Opened 2024-04-30 09:57 UTC by laurasootes

This PR:

Adds episode 2 for the NLP course. It contains various preprocessing steps:

By hand
- reading in the data
- getting sentence tokens
- getting word tokens

Using spacy
- lowercasing
- stopword removal
- lemmatization
- part-of-speech tagging

2024-04-30 12:00 UTC, n400peanuts commented on episodes/episode02.md
> +- Explain what preprocessing means.
type something

2024-04-30 12:01 UTC, n400peanuts commented on episodes/episode02.md
> +- Explain what preprocessing means.
ciao

2024-05-01 09:28 UTC, n400peanuts requested changes
Ciao Laura this looks wonderful. I have left some suggestions and corrected typos but in general I think this covers exactly what we were meant to teach in this lesson, so well done!!!

my main suggestion is to frame at the beginning data preprocessing as a step that is dependent by the nlp task. This might help also in adding the exercise at the end? the rest are very minor suggestions!

2024-05-01 09:28 UTC, n400peanuts commented on episodes/episode02.md
> +nlp = spacy.load('en_code_web_md')
`en_code_web_md` is a model that does not come as a standard in the spacy installation so it might be useful to add instructions on how to download it first (added those in the suggestion above)

also, there is a typo

```suggestion
nlp = spacy.load('en_core_web_md')
```

2024-05-01 09:28 UTC, n400peanuts commented on episodes/episode02.md
> +
instructions to download `en_core_web_md`:


```suggestion
First, ensure that the model is correctly installed in your environment. If not, this code below will do that for you:

```python
!python -m spacy download en_core_web_md
```

```

2024-05-01 09:28 UTC, n400peanuts commented on episodes/episode02.md
> +We load the pipeline that we are going to use which is `en_code_web_md`. This a pipeline that is pretrained to do a number of NLP tasks for English texts. It is important to realize that in many case
corrected typo in the name of the model `core` vs `code`
```suggestion
We load the pipeline that we are going to use which is `en_core_web_md`. This a pipeline that is pretrained to do a number of NLP tasks for English texts. It is important to realize that in many cases you can use a pretrained model such as this one. You then do not have to do any training of your data. This is very nice, because training a model requires a whole lot of data, that would have to be analyzed by hand before you can start. It also requires a lot of specific understanding of NLP and a lot of time, and often it is simply not neccesary. These available models are trained on a lot of data, and have very good accuracy.
```

2024-05-01 09:28 UTC, n400peanuts commented on episodes/episode02.md
> +PUT THIS  IN A SEPARATE FUNCTION THAT IS LOADED INTO THE NOTEBOOK
I suggest removing the following sentence as this is meant to be read for the instructors. Perhaps this is something we can add to the instructors folder? not sure how would this work though

```suggestion
```

2024-05-01 09:28 UTC, n400peanuts commented on episodes/episode02.md
> +from wordcloud import WordCloud
I suggest removing this import as you already have imported wordcloud above in the notebook

```suggestion
```

2024-05-01 09:28 UTC, n400peanuts commented on episodes/episode02.md
> +
FYI We can add images in the md, it would help to the reader to know if they got the same output as you. Maybe worth considering if you have time?

2024-05-01 09:28 UTC, n400peanuts commented on episodes/episode02.md
The challenge above is a proposal for an exercise -- would that work for you? is there anything else we could have? if so, might be useful to add a solution as well in the tag below

2024-05-01 10:05 UTC, laurasootes commented on episodes/episode02.md
> +- What different types of preprocessing steps are there?
What did you mean to add here? It seems that the suggested addition is missing

2024-05-01 10:09 UTC, laurasootes commented on episodes/episode02.md
> +- Explain what preprocessing means.
isn't the original phrasing correct?

2024-05-01 10:15 UTC, laurasootes commented on episodes/episode02.md
> +have a list of words in a piece of text arranged with their parts of speech and lemmas or stems, and with very frequent words removed
I have now added: "be able to apply and use a spacy pretrained model"

2024-05-01 10:24 UTC, laurasootes commented on episodes/episode02.md
> +
I added you suggestions with some slight modification

2024-05-01 10:27 UTC, laurasootes commented on episodes/episode02.md
> +- lemmatization: here you would get the lemma of each word. You would get the form in which you find the word in the dictionary, such as the singular version of a plural of a noun, or the first perso
I agree that it is confusion. I think that it might be better to omit stemming and only include lemmatization here?

2024-05-01 10:32 UTC, laurasootes commented on episodes/episode02.md
> +- part of speech tagging. This means that you identify what type of word each is; such as nouns and verbs.
We can also just leave it for now and see if others give comments on this

2024-05-01 13:51 UTC, laurasootes commented on episodes/episode02.md
> +nlp = spacy.load('en_code_web_md')
I also added some stuff on pretrained models from Hugging Face

2024-05-01 14:59 UTC, n400peanuts approved these changes

2024-05-02 09:42 UTC, merged