18 develop episode 3
esciencecenter-digital-skills/Natural-language-processing pull request #19
Opened 2024-07-16 12:34 UTC by n400peanuts

2024-07-17 13:17 UTC, angel-daza commented on episodes/03-embeddings.md
> +words = ["the", "cat", "sat", "on", "the","mat"]
this variable should be `sentence` and the following should be `words`

2024-07-17 13:18 UTC, angel-daza commented on episodes/03-embeddings.md
> +table = ax.table(cellText=data, rowLabels=words, colLabels=sentence, cellLoc='center', loc='center')
I guess then the wordLabels and colLabels should also be swaped

2024-07-17 13:29 UTC, angel-daza commented on episodes/fig/emb6.png
The "paste" sign still appears in the screenshot

2024-07-17 13:33 UTC, angel-daza commented on episodes/03-embeddings.md
> +Which of these two animals (dog vs caterpillar) is more similar to a cat? We can compute the similarity among those vectors with the function `cosine_similarity()` in Python, from the `sklearn` libra
It may be useful to mention here what cosine_similarity() does and why it is a useful metric of similarity (since it is already visible in your nice example pics that the similar vectors have a small angle, etc...)

2024-07-17 13:42 UTC, angel-daza commented on episodes/03-embeddings.md
> +- Dimensions in word embeddings are many and not transparent
Dimensions in **corpus-based** word embeddings? Just to make clear this was only an example and is not normally how the word embeddings are constructed...

2024-07-17 13:48 UTC, angel-daza commented on episodes/03-embeddings.md
> +We use the trained word2vec model named `GloVe` from the `gensim` library. The GloVe embeddings was trained on an English Wikipedia dump and English Gigaword 5th Edition dataset. It has 6B tokens. Th
This is actually not the best because GloVe is a separate algorithm used to compute distributed word representations, it is like the "competitor" of word2vec. Maybe just use the google-news-300? That is usually considered the vanilla word2vec

2024-07-17 13:58 UTC, angel-daza commented on episodes/03-embeddings.md
> +Word2Vec is a two-layer neural network that processes raw text and returns us the respective word-vectors (i.e., *word embeddings*). To use it, we have two choices: Train a word2vec model on our own
It is always useful to mention that there are two different network architectures: Continuous bag-of-words `CBOW` and `Skip-gram`. Seeing how these 2 strategies work actually allows you to understand the intuition behind the word representations of word2vec.  In `CBOW` a network uses the context as input and is trained to predict the target (middle) word, whereas in skip-gram the network takes a target word as input and is trained to predict the surrounding words. This is why words that appear together with similar words will end up with similar vector weights.

2024-07-17 14:00 UTC, angel-daza commented on episodes/03-embeddings.md
> +Output:
In general, it will be useful to differentiate word2vec (the most famous strategy to compute distributed word representations) from other strategies to obtain word representations, i.e. fasttext, glove, conceptnet, etc...

2024-07-17 14:03 UTC, angel-daza commented on episodes/03-embeddings.md
> +We can see that although both vectors have the same number of dimensions, they seem to have similar values (i.e., colours) for some of them. Does this mean that they map the same features?
This might be too misleading because the whole vector is the one feature that represents a word type, the isolated dimensions are really meaningless in these kind of embeddings. They might end up coincidentally encoding an aspect of the co-ocurrences of the entries but this is corpus-specific and more importantly hyperparameter-specific. So perhaps this is too risky to say...

2024-07-17 14:04 UTC, angel-daza commented on episodes/03-embeddings.md
> +A famous analogy (King - man + woman ~= queen) shows an incredible property of word embeddings: That is, since words are encoded as vectors, we can often solve analogies with vector arithmetic.
of `word2vec embeddings`

2024-07-17 14:19 UTC, angel-daza commented on episodes/03-embeddings.md
> +At a closer inspection, however, there is also an interesting phenomenon visible: The words `fly` (for animals) and `bobcat` (for vehicles) are somewhat confused. They are represented closer to the v
And the reason why it is not able to do it is because it crams in a single vector all meanings of the same word entry. So the vector `fly` is optimized to represent at the same time verb `fly` and the noun `fly`, creating the "confusion". Most of the times the vector converges towards the most frequently use of the word entry, which is not always what we want...

2024-07-17 14:23 UTC, angel-daza commented on episodes/03-embeddings.md
> +            tokens = [token.text.lower() for token in sentence if not token.is_stop and not token.is_punct]
If you want to get less "crappy" results in this mini model you could train the lemmas token.lemma.lower() and also ignore all of the words that start with uppercase (so less Named Entities).

2024-07-17 14:25 UTC, angel-daza requested changes
I like that you want to make the "embedding" idea very intuitive and in fact I think you managed well! Most comments are for clarifying some conceptual confusions

2024-07-22 11:35 UTC, n400peanuts commented
All comments have been addressed -- I am requesting a final check

2024-07-24 07:48 UTC, angel-daza commented on episodes/03-embeddings.md
> +![Embedding of king - word2vec model](fig/emb7.png){alt=""}
This `{alt=""}` appears to be rendered next to the image. Perhaps is just an error in the github viewer?

2024-07-24 07:50 UTC, angel-daza approved these changes

2024-07-25 07:59 UTC, merged